### ISSUE TITLE
📢📢📢 known limitations

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-go-core#1]
Hi everyone and thanks for trying our preview of the Microsoft Graph Go SDK built on our [next generation generator kiota](https://github.com/microsoft/kiota).

This issue is here to list out all the limitations we're currently aware of, we'll try to tackle them as soon as possible.

Please go upvote the linked issues if this is something that's limiting your usage of the SDK, so we know which feature to prioritize.

List of limitations:
- [ ] [Multi-part content](https://github.com/microsoft/kiota/issues/220)
- [ ] #12 
- [x] [Backing store support for dirty tracking of changed properties](https://github.com/microsoft/kiota/issues/466)
- [x] #95 
- [x] #106
- [x] #31
- [x] #11 
- [x] [use of generics to reduce build time further](https://github.com/microsoft/kiota/issues/1404)
- [x] #15
- [x] #6
- [x] #26
- [x] [Missing middleware for chaos (unit testing)](https://github.com/microsoft/kiota/issues/371)
- [x] [OData downcast support for mixed collections](https://github.com/microsoft/kiota/issues/648)
- [x] [The parsable interface needs to be splat](https://github.com/microsoft/kiota/issues/737)
- [x] [errors returned by the service are not deserialized](https://github.com/microsoft/kiota/issues/411)
- [x] #28
- [x] #14
- [x] [paging through collections](https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/13)
- [x] #2
- [x] [Doc comment support](https://github.com/microsoft/kiota/issues/746)
- [x] [Missing middleware for transient error retrial](https://github.com/microsoft/kiota/issues/371)
- [x] [Missing middleware for redirection](https://github.com/microsoft/kiota/issues/371)
- [x] [Optional parameters support - everything is required](https://github.com/microsoft/kiota/issues/469)
- [x] [No snippets present in the Graph Explorer/public documentation](https://github.com/microsoft/kiota/issues/388)
- [x] [Issue when compiling due do azure identity/core](https://github.com/microsoft/kiota/issues/783)

> Note : a checkmark means the issue has been resolved since the initial release.

Also please [be aware that some of the libraries this SDK depends on](https://github.com/microsoft/kiota/issues/370) will move at the end of the preview, so expect breaking changes to happen multiple times!

**Comment by gajawadaprashanth** [comment]
Hi,
I was trying to integrate Microsoft Graph API into my go Application. I have followed all the instruction mentioned in this url: https://learn.microsoft.com/en-us/graph/tutorials/go?tabs=aad and I have struck with one package problem which is not implemented it. i got this error: MeMailFoldersItemMessagesRequestBuilderGetRequestConfiguration not declared by packagem, NewMeSendMailPostRequestBody not declared by package models these two errors i got even i declared the package. can you please update this package asap.

**Comment by baywet** [comment]
@gajawadaprashanth can you create a separate issue for this please?

**Comment by gajawadaprashanth** [comment]
Sure, I have Created as new issue @baywet
