### ISSUE TITLE
[Tracking[ GraphClientFactory

### ISSUE THREAD

**Issue by jobala** [microsoftgraph/msgraph-sdk-go-core#6]
- [ ] Configure request timeout to **100secs**
- [ ] Configure  connection timeout to **30secs**
- [x] Allow users to pass their own HTTP client
- [x] Support attaching middleware pipeline to existing http client
- [x] Set sdk version header
- [x] Support custom hosts
- [x] Create instance of GraphClient with user defined middleware and default middleware
- [x] Create instance of GraphClient with default middleware

**Comment by baywet** [comment]
Thanks for the feedback on this one @jobala !
Some of the things have been addressed since you created this issue, so I took the liberty to check these off.
For others, that'd require more significant work, I created dedicated issues for them.
For sovereign cloud/custom hosts, we've had a discussion on the topic with @andrueastman [here](https://github.com/microsoft/kiota/issues/785) it's part of the planned changes in Kiota.

Would you mind taking on the time out configuration please?

**Comment by baywet** [comment]
PS: I believe the timeout configuration should live in Kiota http, not in this core directly.

**Comment by baywet** [comment]
update: setting a custom host is not supported through `requestAdapter.SetBaseUrl("https://thebaseurl")`
Note: this needs to be set after passing the request adapter to a GraphServiceClient as the graph service client constructor also calls that method.
